import { FarmerList } from "../interface/farmer";

let FARMER_DATA: FarmerList[] = [
  {
    position: 1,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 2,
    farmer_code: 'CBF069',
    farmer_name: 'Maksudan Chandra',
    district_name: 'Raigarh',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 3,
    farmer_code: 'CBF069',
    farmer_name: 'Dilip Banjare',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 4,
    farmer_code: 'CBF069',
    farmer_name: 'Sammelal Sahu',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 5,
    farmer_code: 'CBF069',
    farmer_name: 'Mukesh Shriwas',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 6,
    farmer_code: 'CBF069',
    farmer_name: 'Chandrika Prasad Sahu',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 7,
    farmer_code: 'CBF069',
    farmer_name: 'Vijay Kumar Banjare',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 8,
    farmer_code: 'CBF069',
    farmer_name: 'Sukhsagar Barman',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 9,
    farmer_code: 'CBF069',
    farmer_name: 'Om Prakash',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 10,
    farmer_code: 'CBF069',
    farmer_name: 'Yogesh Kumar Chandra',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 11,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 12,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 13,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 14,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 15,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 16,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 17,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 18,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 19,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 20,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 21,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 22,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 23,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 24,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  },
  {
    position: 25,
    farmer_code: 'CBF069',
    farmer_name: 'Lekh Ram',
    district_name: 'Janjgir',
    branch_name: 'Janjgir',
    line_name: 'Janjgir Naila-West',
    village_name: 'Mukta',
    aggrement_no: 'CGA/007/2022-23',
    contact_no: '7898026169',
    guarantor_name: 'LEKH RAM',
    emp_name: 'Sanjeev Kumar'
  }
];

export { FARMER_DATA };